import './globals.css';
import { ClientCookiesProvider } from '@/CookieProvdier';
import { cookies } from 'next/headers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Providers } from '@/redux/provider';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function checkLogin() {
  //returns username if true.Replaces login button
  const cookieStore = cookies();
  const user = cookieStore.get('user');
  return user?.value;

}


export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  const user = checkLogin();

  let signInButton;

  user ? signInButton = <p>{user}</p> : signInButton = <Link href={{ pathname: '/login', query: { entry: 'login' } }}>Login</Link>;


  return (
    <Providers>
      <ClientCookiesProvider value={cookies().getAll()}>
        <html lang="en">
          <body className={inter.className}>
            <header>
              <h1>This is Jeopardy</h1>
              {signInButton}
            </header>
            {children}
            <Analytics />
          </body>
        </html>
      </ClientCookiesProvider>
    </Providers>
  );
}
